// Copyright 2023 Microsoft, Inc
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef CHROHIME_C_CHROHIME_H_
#define CHROHIME_C_CHROHIME_H_

#include "chrohime/c/chrohime_c_impl.inc"

#if defined(CHROHIME_C_IMPLEMENTATION)
#include "chrohime/api/chrohime.h"
#endif

// The actual headers are automatically generated by generate_c_impls.py
#include "chrohime/c/generated_impls.h"

#endif  // CHROHIME_C_CHROHIME_H_
