// Copyright 2023 Microsoft, Inc
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "chrohime/dylib/chrohime.h"
#include "ui/gfx/geometry/rect.h"

// The actual implementations are automatically generated by generate_c_impls.py
#include "chrohime/dylib/generated_impls.cc"
