// Copyright 2023 Microsoft, Inc
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "chrohime/api/chrohime.h"
#include "chrohime/dylib/chrohime_c_impl.inc"
#include "chrohime/dylib/skia.h"
#include "ui/gfx/geometry/rect.h"  // needed by impls.cc

namespace {

// A helper used by xx_on_event_connect implementations.
class DataHolder : public base::RefCounted<DataHolder> {
 public:
  REQUIRE_ADOPTION_FOR_REFCOUNTED_TYPE();

  DataHolder(void* data, hime_free_callback free) : data_(data), free_(free) {}

  void* data() const { return data_.get(); }

 private:
  friend class base::RefCounted<DataHolder>;

  ~DataHolder() {
    if (free_)
      free_(data_);
  }

  raw_ptr<void> data_;
  hime_free_callback free_;
};

}  // namespace

// The actual implementations are automatically generated by generate_c_impls.py
#include "chrohime/dylib/generated_impls.h"
#include "chrohime/dylib/generated_impls.cc"
