name: Build Chrohime

on:
  push:
  # Allow running manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: >-
      ${{
        (matrix.targetOs == 'linux' && matrix.config == 'Release') &&
          'ubuntu-latest-m' ||
          (fromJson('{"linux":"ubuntu-22.04","mac":"macos-13","win":"windows-2022"}')[matrix.targetOs])
      }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        targetOs: [linux, mac, win]
        targetCpu: [x64, arm64]
        config: [Component, Release]
        exclude:
          # Do Release build for tags.
          - config: ${{ startsWith(github.ref, 'refs/tags/') && 'Component' || 'Release' }}

    steps:
      - name: Mount workspace to /mnt
        if: runner.os == 'Linux'
        run: |
          sudo mkdir /mnt/work
          sudo mount --bind /mnt/work ${{ github.workspace }}
          sudo chown runner:runner ${{ github.workspace }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: python -m pip install pyyaml httplib2

      - name: Use XCode 15
        if: runner.os == 'macOS'
        run: |
          XCODE_APP=$(find /Applications -maxdepth 1 -type d -name "Xcode_15.*" -print -quit)
          echo 'Using' $XCODE_APP
          sudo xcode-select --switch $XCODE_APP
          echo "XCODE_APP=$XCODE_APP" >> "$GITHUB_ENV"

      - name: Free Disk Spaces
        if: runner.os == 'macOS' && matrix.targetCpu == 'arm64'
        run: |
          UNUSED_XCODE_APPS=$(find /Applications -maxdepth 1 -type d -name "Xcode*" -print | grep -v $XCODE_APP)
          sudo rm -rf $UNUSED_XCODE_APPS

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install gperf
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Bootstrap
        run: python3 scripts/bootstrap.py --target-cpu ${{ matrix.targetCpu }}

      - name: Setup Reclient
        env:
          ELECTRON_RBE_JWT: ${{ secrets.RBE_SECRET }}
        run: node third_party/build_chromium/reclient.js login

      - name: GN Gen
        shell: bash
        run: python3 scripts/gn_gen.py --reclient --config ${{ matrix.config }} --target-cpu ${{ matrix.targetCpu }} --arg 'chrohime_version="${{ github.ref_name }}"'

      - name: Component Build
        if: matrix.config == 'Component'
        run: python3 scripts/build.py chrohime_gallery

      - name: Test Component Build
        if: matrix.config == 'Component' && matrix.targetCpu == 'x64'
        env:
          DISPLAY: ':99.0'
        run: ./chromium/out/Component/chrohime_gallery --test

      - name: Build Chrohime Shared Library
        # The no_content lib does not work on mac yet.
        if: matrix.targetOs != 'mac'
        run: python3 scripts/build.py --config ${{ matrix.config }} chrohime_zip

      - name: Build ChrohimeWithContent Shared Library
        run: python3 scripts/build.py --config ${{ matrix.config }} chrohime_with_content_zip

      - name: Test Shared Libraries
        if: matrix.config == 'Release' && matrix.targetCpu == 'x64'
        env:
          DISPLAY: ':99.0'
        run: python3 scripts/test_dist.py

      - name: Build Documentations
        if: matrix.targetOs == 'linux' && matrix.targetCpu == 'x64'
        run: python3 scripts/build.py --config ${{ matrix.config }} chrohime_docs_zip chrohime_apis_json_zip

      - name: Upload Zip Distributions
        uses: actions/upload-artifact@v3
        with:
          path: chromium/out/${{ matrix.config }}/*.zip
          retention-days: 1

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Files
        uses: actions/download-artifact@v3

      - name: List Download Files
        run: ls -lh artifact

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          name: Chrohime ${{ github.ref_name }}
          bodyFile: dylib/ZIP_DESCRIPTION.md
          draft: true
          artifacts: artifact/*.zip
          artifactErrorsFailBuild: true
