name: chrohime

on: push

jobs:
  build:
    runs-on: >-
      ${{
        (matrix.targetOs == 'linux' && matrix.config == 'Release') &&
          'ubuntu-latest-m' ||
          (fromJson('{"linux":"ubuntu-22.04","mac":"macos-13","win":"windows-2022"}')[matrix.targetOs])
      }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        targetOs: [linux, mac, win]
        targetCpu: [x64, arm64]
        config: [Component, Release]
        exclude:
          # Do Release build for tags.
          - config: ${{ startsWith(github.ref, 'refs/tags/') && 'Component' || 'Release' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: python -m pip install pyyaml httplib2

      - name: Use XCode 15
        if: runner.os == 'macOS'
        run: |
          XCODE_APP=$(find /Applications -maxdepth 1 -type d -name "Xcode_15.*" -print -quit)
          echo 'Using' $XCODE_APP
          sudo xcode-select --switch $XCODE_APP

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install gperf
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Bootstrap
        run: python3 scripts/bootstrap.py --target-cpu ${{ matrix.targetCpu }}

      - name: Setup GOMA
        shell: bash
        env:
          SECRET_FILE_CONTENT: ${{ secrets.GOMA_OAUTH2_CONFIG }}
        run: |
          printf "$SECRET_FILE_CONTENT" > ~/.goma_oauth2_config
          node third_party/build_chromium/goma.js

      - name: GN Gen
        shell: bash
        run: python3 scripts/gn_gen.py --goma --config ${{ matrix.config }} --target-cpu ${{ matrix.targetCpu }} --arg 'chrohime_version="${{ github.ref_name }}"'

      - name: Component Build
        if: matrix.config == 'Component'
        run: python3 scripts/build.py chrohime_gallery chrohime_dylib chrohime_with_content_dylib

      - name: Build Chrohime Shared Library
        # The no_content lib does not work on mac yet.
        if: matrix.config == 'Release' && matrix.targetOs != 'mac'
        run: python3 scripts/build.py --config Release chrohime_zip

      - name: Build ChrohimeWithContent Shared Library
        # The with_content lib does not link on linux yet, wait for below CL to
        # land in dev channel:
        # https://chromium-review.googlesource.com/c/chromium/src/+/5119971
        if: matrix.config == 'Release' && matrix.targetOs != 'linux'
        run: python3 scripts/build.py --config Release chrohime_with_content_zip

      - name: Test Shared Libraries
        if: matrix.config == 'Release' && matrix.targetCpu == 'x64'
        run: python3 scripts/test_dist.py

      - name: Upload Shared Libraries
        if: matrix.config == 'Release'
        uses: actions/upload-artifact@v3
        with:
          path: chromium/out/Release/*.zip
          retention-days: 1

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Files
        uses: actions/download-artifact@v3

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: Chrohime ${{ github.ref_name }}
          body: '## Changelog'
          draft: true
          artifacts: artifact/*.zip
          artifactErrorsFailBuild: true
